### ISSUE TITLE
your RocketRAID 62x SATA Controller driver "works or not" on 10.13."6" ?

### ISSUE THREAD

**Issue by vacarogit** [alessandro893/RocketRaid62X#1]
Hello goof alessandro893,

Have you updated your OS to 10.13+?
I have a 622 card and =DPCI manager shows below, photo attached. (same as yours??)
"1103, 0622, 1103, 0001, HighPoint Technologies, Inc., RocketRAID 622 2 Port SATA-III Controller"

I use this card's eSATA port, in Windows 7, everything works, in Hackintosh 10.13+ (10.12.6) are like dead or not installed. 
Tried different kexts and even mod kext, no luck. 

Strangely, I saw your kext set yesterday and I installed, I found that both HighPointIOP & RR loaded the first-time reboot, and my eSATA enclosure can see all drives, so I regard it works and want to say Thank you.
BUT, my next and many other reboot failed to load "HighPointIOP", RR is loaded, the drive is not recognizable anymore, soo strange.

If you are in 10.13+, would you mind sharing your working version of kext or direct where to download?
I saw another post direct to version 1.0 or 1.1.x but they all seem very old I have no faith in them.

(additional info: due to this Raid card always takes too much time to load its useless bios in booting , I have flashed the card with non-bootrom bios, I think that may or may not be the cause, whatever, your comment would help! )

**Comment by alessandro893** [comment]
Hello. It is original Highpoint driver from Mac OS X 10.9.5. 
I can't test it on 10.13, because I'm not using Hackintosh anymore. 
‼️‼️‼️ If it's worked once, then it must start working again ‼️‼️‼️

try:
1. Set kext-dev-mode=1 in bootloader
2. Rebuild cache via Kext Utility.app
3. Try to install kexts in Clover's EFI partition (and delete all HighPoint kexts from /Library/Extensions/)

I think that 'non-bootrom bios' can't cause this issue, because apple uses EFI instead of BIOS, and your card worked at first boot.

Can you upload photo again?
